#index:
#    path: /
#    controller: App\Controller\DefaultController::index

live_component:
    resource: '@LiveComponentBundle/config/routes.php'
    # uncomment to add localization to your components
    #prefix: '/{_locale}'

#discord_login:
#    path: /login/discord
